In [1]:
import pandas as pd

In [5]:
df = pd.read_excel('raffle_dfs/MAIC_ Holiday Celebration Raffle.xlsx')

# Grab only the last two columns of the DataFrame
df = df.iloc[:, -2:]
df

     First and Last Name  How Many Points Would You Like to Spend?
0    Ryan Pal Hilgendorf                                         2
1      Sebastian Dolecki                                         4
2          Noah nieberle                                         0
3       Theodore Schmitt                                         1
4         Andrew Needham                                         0
5             Sam Keyser                                        22
6          Vincenzo Bean                                         3
7          will lassiter                                         2
8             Alex Ewart                                         2
9          Adam Swedlund                                         0
10          Michael Wood                                         0
11            Caleb Gray                                        10
12      Madison Engebose                                         3
13       Rebecca Colwell                                         0
14       Peter Kwaterski                                         4
15         Theodore Rett                                         0
16          Autumn Mizer                                         1
17          Autumn Mizer                                         0
18          Colton Waltz                                         0
19           Lexi Dorner                                         0
20      Gabrielle Sladek                                         0
21          Mason Beynon                                         0
22          Jake Weiland                                         0
23             Ryan Kruk                                         1
24          Austin Koske                                         0
25           Hayden Park                                         0
26          Aaron herbst                                         1
27       Josiah Reinholz                                         2
28       cameron delpage                                         0
29            Xander Ede                                         0
30      Patrick Rafferty                                         0
31    Wendpanga Tapsoba                                          1
32     andrew gilpatrick                                         1
33       Alexander Lopez                                         4
34      Mikhail Filippov                                         2
35      Reagan Burkemper                                         0
36        Oskar Sierzega                                        10
37     Giovanni Martinez                                         0
38           Zak Goetter                                         2
39          Jack LeCloux                                         1
40         Jayden Hudson                                         1
41           Vlad Wilson                                         0
42   Savanna Sam McClure                                         1
43        Kathlyn Leaños                                         5
44         Jasdeep Singh                                         2
45  Adrianne Schellinger                                        30
46      Travis Jankowski                                         3
47       Josephine Dobbs                                         0
48           Zoe Kirkman                                         0
49        Joseph Beattie                                         3
50        Jaden griffith                                         2
51       Charlie Nortrup                                         0
52         Bjarne Baasch                                         1
53          Madison Mina                                         1
54        Kelsey Collins                                         3
55       Miles Trompeter                                         4
56      Spencer Guercio                                          0
57    Mitchell Johnstone                                         0
58           Dimas Monte                                         9
59      Preston Whitcomb                                         1

### Create a list that is Easy to Input Into Online Roulette Wheel
https://wheelofnames.com/

In [7]:
# Given the dataframe, create a new dataframe where a name is repeated x number of rows, where x is the number denoted in the second column. If the number is NaN or 0, then inlcude the person only once

# Create a new dataframe
entries = []

# Iterate through each row in the dataframe

for index, row in df.iterrows():
    # Get the name and number of times to repeat
    name = row[-2]
    num = row[-1]
    
    # If the number is NaN or 0, then include the person only once
    if pd.isnull(num) or num == 0:
        entries.append(name)
    else:
        # Repeat the person x number of times
        for i in range(int(num) + 1):
            entries.append(name)

entries

/var/folders/n0/lqgykh5n5s5f6fk5p0s0bjd00000gn/T/ipykernel_75244/407161840.py:10: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  name = row[-2]
/var/folders/n0/lqgykh5n5s5f6fk5p0s0bjd00000gn/T/ipykernel_75244/407161840.py:11: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  num = row[-1]

['Ryan Pal Hilgendorf',
 'Ryan Pal Hilgendorf',
 'Ryan Pal Hilgendorf',
 'Sebastian Dolecki',
 'Sebastian Dolecki',
 'Sebastian Dolecki',
 'Sebastian Dolecki',
 'Sebastian Dolecki',
 'Noah nieberle',
 'Theodore Schmitt',
 'Theodore Schmitt',
 'Andrew Needham',
 'Sam Keyser',
 'Sam Keyser',
 'Sam Keyser',
 'Sam Keyser',
 'Sam Keyser',
 'Sam Keyser',
 'Sam Keyser',
 'Sam Keyser',
 'Sam Keyser',
 'Sam Keyser',
 'Sam Keyser',
 'Sam Keyser',
 'Sam Keyser',
 'Sam Keyser',
 'Sam Keyser',
 'Sam Keyser',
 'Sam Keyser',
 'Sam Keyser',
 'Sam Keyser',
 'Sam Keyser',
 'Sam Keyser',
 'Sam Keyser',
 'Sam Keyser',
 'Vincenzo Bean',
 'Vincenzo Bean',
 'Vincenzo Bean',
 'Vincenzo Bean',
 'will lassiter',
 'will lassiter',
 'will lassiter',
 'Alex Ewart',
 'Alex Ewart',
 'Alex Ewart',
 'Adam Swedlund',
 'Michael Wood',
 'Caleb Gray',
 'Caleb Gray',
 'Caleb Gray',
 'Caleb Gray',
 'Caleb Gray',
 'Caleb Gray',
 'Caleb Gray',
 'Caleb Gray',
 'Caleb Gray',
 'Caleb Gray',
 'Caleb Gray',
 'Madison Engebose',
 'Madison Engebose',
 'Madison Engebose',
 'Madison Engebose',
 'Rebecca Colwell',
 'Peter Kwaterski',
 'Peter Kwaterski',
 'Peter Kwaterski',
 'Peter Kwaterski',
 'Peter Kwaterski',
 'Theodore Rett',
 'Autumn Mizer',
 'Autumn Mizer',
 'Autumn Mizer',
 'Colton Waltz',
 'Lexi Dorner',
 'Gabrielle Sladek',
 'Mason Beynon',
 'Jake Weiland',
 'Ryan Kruk',
 'Ryan Kruk',
 'Austin Koske',
 'Hayden Park',
 'Aaron herbst',
 'Aaron herbst',
 'Josiah Reinholz',
 'Josiah Reinholz',
 'Josiah Reinholz',
 'cameron delpage',
 'Xander Ede',
 'Patrick Rafferty',
 'Wendpanga Tapsoba ',
 'Wendpanga Tapsoba ',
 'andrew gilpatrick',
 'andrew gilpatrick',
 'Alexander Lopez',
 'Alexander Lopez',
 'Alexander Lopez',
 'Alexander Lopez',
 'Alexander Lopez',
 'Mikhail Filippov',
 'Mikhail Filippov',
 'Mikhail Filippov',
 'Reagan Burkemper',
 'Oskar Sierzega',
 'Oskar Sierzega',
 'Oskar Sierzega',
 'Oskar Sierzega',
 'Oskar Sierzega',
 'Oskar Sierzega',
 'Oskar Sierzega',
 'Oskar Sierzega',
 'Oskar Sierzega',
 'Oskar Sierzega',
 'Oskar Sierzega',
 'Giovanni Martinez',
 'Zak Goetter',
 'Zak Goetter',
 'Zak Goetter',
 'Jack LeCloux',
 'Jack LeCloux',
 'Jayden Hudson',
 'Jayden Hudson',
 'Vlad Wilson',
 'Savanna Sam McClure',
 'Savanna Sam McClure',
 'Kathlyn Leaños',
 'Kathlyn Leaños',
 'Kathlyn Leaños',
 'Kathlyn Leaños',
 'Kathlyn Leaños',
 'Kathlyn Leaños',
 'Jasdeep Singh',
 'Jasdeep Singh',
 'Jasdeep Singh',
 'Adrianne Schellinger',
 'Adrianne Schellinger',
 'Adrianne Schellinger',
 'Adrianne Schellinger',
 'Adrianne Schellinger',
 'Adrianne Schellinger',
 'Adrianne Schellinger',
 'Adrianne Schellinger',
 'Adrianne Schellinger',
 'Adrianne Schellinger',
 'Adrianne Schellinger',
 'Adrianne Schellinger',
 'Adrianne Schellinger',
 'Adrianne Schellinger',
 'Adrianne Schellinger',
 'Adrianne Schellinger',
 'Adrianne Schellinger',
 'Adrianne Schellinger',
 'Adrianne Schellinger',
 'Adrianne Schellinger',
 'Adrianne Schellinger',
 'Adrianne Schellinger',
 'Adrianne Schellinger',
 'Adrianne Schellinger',
 'Adrianne Schellinger',
 'Adrianne Schellinger',
 'Adrianne Schellinger',
 'Adrianne Schellinger',
 'Adrianne Schellinger',
 'Adrianne Schellinger',
 'Adrianne Schellinger',
 'Travis Jankowski',
 'Travis Jankowski',
 'Travis Jankowski',
 'Travis Jankowski',
 'Josephine Dobbs',
 'Zoe Kirkman',
 'Joseph Beattie',
 'Joseph Beattie',
 'Joseph Beattie',
 'Joseph Beattie',
 'Jaden griffith',
 'Jaden griffith',
 'Jaden griffith',
 'Charlie Nortrup',
 'Bjarne Baasch',
 'Bjarne Baasch',
 'Madison Mina',
 'Madison Mina',
 'Kelsey Collins',
 'Kelsey Collins',
 'Kelsey Collins',
 'Kelsey Collins',
 'Miles Trompeter',
 'Miles Trompeter',
 'Miles Trompeter',
 'Miles Trompeter',
 'Miles Trompeter',
 'Spencer Guercio ',
 'Mitchell Johnstone',
 'Dimas Monte',
 'Dimas Monte',
 'Dimas Monte',
 'Dimas Monte',
 'Dimas Monte',
 'Dimas Monte',
 'Dimas Monte',
 'Dimas Monte',
 'Dimas Monte',
 'Dimas Monte',
 'Preston Whitcomb',
 'Preston Whitcomb']

### Better DF Format
Get the df into a format which is easy to remove the points from the online leaderboard

In [8]:
# For df, replace all Nan values with 0 (Free point)
df = df.fillna(0)

# Rename the first column to 'Name' and the second column to 'Points'
df.columns = ['Name', 'Points']
df

# For each name, get rid of white space surrounding the name and title the string
df['Name'] = df['Name'].str.strip().str.title()
df

                    Name  Points
0    Ryan Pal Hilgendorf       2
1      Sebastian Dolecki       4
2          Noah Nieberle       0
3       Theodore Schmitt       1
4         Andrew Needham       0
5             Sam Keyser      22
6          Vincenzo Bean       3
7          Will Lassiter       2
8             Alex Ewart       2
9          Adam Swedlund       0
10          Michael Wood       0
11            Caleb Gray      10
12      Madison Engebose       3
13       Rebecca Colwell       0
14       Peter Kwaterski       4
15         Theodore Rett       0
16          Autumn Mizer       1
17          Autumn Mizer       0
18          Colton Waltz       0
19           Lexi Dorner       0
20      Gabrielle Sladek       0
21          Mason Beynon       0
22          Jake Weiland       0
23             Ryan Kruk       1
24          Austin Koske       0
25           Hayden Park       0
26          Aaron Herbst       1
27       Josiah Reinholz       2
28       Cameron Delpage       0
29            Xander Ede       0
30      Patrick Rafferty       0
31     Wendpanga Tapsoba       1
32     Andrew Gilpatrick       1
33       Alexander Lopez       4
34      Mikhail Filippov       2
35      Reagan Burkemper       0
36        Oskar Sierzega      10
37     Giovanni Martinez       0
38           Zak Goetter       2
39          Jack Lecloux       1
40         Jayden Hudson       1
41           Vlad Wilson       0
42   Savanna Sam Mcclure       1
43        Kathlyn Leaños       5
44         Jasdeep Singh       2
45  Adrianne Schellinger      30
46      Travis Jankowski       3
47       Josephine Dobbs       0
48           Zoe Kirkman       0
49        Joseph Beattie       3
50        Jaden Griffith       2
51       Charlie Nortrup       0
52         Bjarne Baasch       1
53          Madison Mina       1
54        Kelsey Collins       3
55       Miles Trompeter       4
56       Spencer Guercio       0
57    Mitchell Johnstone       0
58           Dimas Monte       9
59      Preston Whitcomb       1

In [16]:
user_data = pd.read_csv('../../data/User_Data.csv')
user_data

,User,Description,Awards,All-Time Points,Current Points,First Name,Last Name
0,Ben Paulson,test description,Hacksgiving|ROSIE Competition Finalist 2024|NV...,54,49,Ben,Paulson
1,Lucas Gral,test description,Overlord|eboard2022|eboard2023|eboard2024|2022...,37,37,Lucas,Gral
2,Sydney Balboni,test description,ROSIE Presenter|Hacksgiving|2024 Researcher|20...,48,47,Sydney,Balboni
3,John Cisler,test description,Hacksgiving|ROSIE Competition Finalist 2024|RO...,15,14,John,Cisler
4,Evan Schubert,test description,2024 Researcher|2024 MICS Attendee,13,13,Evan,Schubert
...,...,...,...,...,...,...,...
344,Adam Swedlund,test description,NaN,11,11,NaN,NaN
345,Eddy Chukwuma-Ugwu,test description,NaN,1,1,NaN,NaN
346,Gideon Stephenson,test description,NaN,1,1,NaN,NaN
347,Joshua Dascoli,test description,NaN,1,1,NaN,NaN
348,Julian,test description,NaN,1,1,NaN,NaN

In [17]:
user_data[user_data['User'] == 'Caleb Gray']

,User,Description,Awards,All-Time Points,Current Points,First Name,Last Name
141,Caleb Gray,test description,2024 Researcher|2024 MICS Attendee|ROSIE Compe...,38,38,Caleb,Gray

In [18]:
# Given the amount of points associated with each Name in df, remove those points from user_data 'Current Points'
for index, row in df.iterrows():
    name = row['Name']
    points = row['Points']
    
    # Find the index of the name in user_data
    user_index = user_data[user_data['User'] == name]

    # If user index empty, skip
    if user_index.empty:
        continue

    # Get the index of the user
    user_index = user_index.index[0]
    
    # Subtract the points from the 'Current Points' column
    user_data.loc[user_index, 'Current Points'] = user_data.loc[user_index, 'Current Points'] - points

    print(f"Subtracting {points} from {name}'s Current Point, resulting in {user_data.loc[user_index, 'Current Points']}")

user_data[user_data['User'] == 'Caleb Gray']

Subtracting 2 from Ryan Pal Hilgendorf's Current Point, resulting in 0
Subtracting 4 from Sebastian Dolecki's Current Point, resulting in 15
Subtracting 0 from Noah Nieberle's Current Point, resulting in 19
Subtracting 1 from Theodore Schmitt's Current Point, resulting in 0
Subtracting 0 from Andrew Needham's Current Point, resulting in 8
Subtracting 22 from Sam Keyser's Current Point, resulting in -21
Subtracting 3 from Vincenzo Bean's Current Point, resulting in 0
Subtracting 2 from Will Lassiter's Current Point, resulting in 5
Subtracting 2 from Alex Ewart's Current Point, resulting in 13
Subtracting 0 from Adam Swedlund's Current Point, resulting in 11
Subtracting 0 from Michael Wood's Current Point, resulting in 13
Subtracting 10 from Caleb Gray's Current Point, resulting in 28
Subtracting 3 from Madison Engebose's Current Point, resulting in 0
Subtracting 4 from Peter Kwaterski's Current Point, resulting in 0
Subtracting 1 from Autumn Mizer's Current Point, resulting in 21
Subtracting 0 from Autumn Mizer's Current Point, resulting in 21
Subtracting 0 from Colton Waltz's Current Point, resulting in 15
Subtracting 0 from Gabrielle Sladek's Current Point, resulting in 37
Subtracting 0 from Mason Beynon's Current Point, resulting in 13
Subtracting 0 from Jake Weiland's Current Point, resulting in 3
Subtracting 1 from Ryan Kruk's Current Point, resulting in 4
Subtracting 0 from Austin Koske's Current Point, resulting in 20
Subtracting 0 from Hayden Park's Current Point, resulting in 4
Subtracting 1 from Aaron Herbst's Current Point, resulting in 8
Subtracting 2 from Josiah Reinholz's Current Point, resulting in 0
Subtracting 0 from Cameron Delpage's Current Point, resulting in 2
Subtracting 0 from Xander Ede's Current Point, resulting in 8
Subtracting 0 from Patrick Rafferty's Current Point, resulting in 48
Subtracting 1 from Andrew Gilpatrick's Current Point, resulting in 0
Subtracting 4 from Alexander Lopez's Current Point, resulting in 40
Subtracting 2 from Mikhail Filippov's Current Point, resulting in 14
Subtracting 0 from Reagan Burkemper's Current Point, resulting in 12
Subtracting 10 from Oskar Sierzega's Current Point, resulting in 0
Subtracting 0 from Giovanni Martinez's Current Point, resulting in 9
Subtracting 2 from Zak Goetter's Current Point, resulting in 18
Subtracting 1 from Jack Lecloux's Current Point, resulting in 15
Subtracting 1 from Jayden Hudson's Current Point, resulting in 0
Subtracting 0 from Vlad Wilson's Current Point, resulting in 20
Subtracting 5 from Kathlyn Leaños's Current Point, resulting in 9
Subtracting 2 from Jasdeep Singh's Current Point, resulting in 0
Subtracting 3 from Travis Jankowski's Current Point, resulting in 50
Subtracting 0 from Zoe Kirkman's Current Point, resulting in 12
Subtracting 3 from Joseph Beattie's Current Point, resulting in 2
Subtracting 2 from Jaden Griffith's Current Point, resulting in 0
Subtracting 0 from Charlie Nortrup's Current Point, resulting in 4
Subtracting 1 from Bjarne Baasch's Current Point, resulting in 22
Subtracting 1 from Madison Mina's Current Point, resulting in 0
Subtracting 3 from Kelsey Collins's Current Point, resulting in 0
Subtracting 4 from Miles Trompeter's Current Point, resulting in 20
Subtracting 0 from Mitchell Johnstone's Current Point, resulting in 22
Subtracting 9 from Dimas Monte's Current Point, resulting in -1
Subtracting 1 from Preston Whitcomb's Current Point, resulting in 7

,User,Description,Awards,All-Time Points,Current Points,First Name,Last Name
141,Caleb Gray,test description,2024 Researcher|2024 MICS Attendee|ROSIE Compe...,38,28,Caleb,Gray

In [19]:
user_data.to_csv('../../data/User_Data.csv', index=False)