In [2]:
import pandas as pd

In [7]:
df = pd.read_excel('raffle_dfs/MAIC_ Spring Break Celebration Raffle 2025(1-46).xlsx')

# Grab only the last two columns of the DataFrame
df = df.iloc[:, -2:]
df

,First and Last Name (As Displayed on Leaderboard),How Many Points Would You Like to Spend?
0,Ryan Pal Hilgendorf,1
1,Alex Ewart,2
2,Michael Link,0
3,Zoe Kirkman,0
4,Michael Link,0
5,Kathlyn Leanos,5
6,Jack LeCloux,0
7,Mason Beynon,0
8,Hugo garrido-lestache,0
9,Leigh Goetsch,0
10,Vincenzo Bean,0
11,Sydney Balboni,50
12,Kelsey collins,3
13,Alhagie Boye,0
14,Miles Trompeter,4
15,Oskar Sierzega,0
16,Lexi Dorner,0
17,Charles BioloThompson,0
18,Alexander Lopez,0
19,Alex Toma,1
20,Austin Koske,0
21,Reagan Burkemper,0
22,Oliver Grudzinski,0
23,Michael Wood,0
24,Raegan Pelnar,0
25,Isabella Ruiz,0
26,Samantha DeLisi,0
27,Gabrielle Sladek,0
28,Jake Weiland,0
29,Xander Ede,0
30,Mikhail Filippov,4
31,Hayden Park,0
32,Vlad Wilson,0
33,Joseph Beattie,0
34,Andrew Needham,12
35,Benjamin Leshin,4
36,Patrick Rafferty,0
37,Will Lassiter,0
38,Jacob Kyllo,0
39,Zak Goetter,4
40,Trevor Hancock,8
41,Travis Jankowski,1
42,John Balasbas,0
43,Josiah Reinholz,6
44,Owen Jacobsen,0
45,Sydney Madden,0

### Create a list that is Easy to Input Into Online Roulette Wheel
https://wheelofnames.com/

In [8]:
# Given the dataframe, create a new dataframe where a name is repeated x number of rows, where x is the number denoted in the second column. If the number is NaN or 0, then inlcude the person only once

# Create a new dataframe
entries = []

# Iterate through each row in the dataframe

for index, row in df.iterrows():
    # Get the name and number of times to repeat
    name = row[-2]
    num = row[-1]
    
    # If the number is NaN or 0, then include the person only once
    if pd.isnull(num) or num == 0:
        entries.append(name)
    else:
        # Repeat the person x number of times
        for i in range(int(num) + 1):
            entries.append(name)

entries

/var/folders/n0/lqgykh5n5s5f6fk5p0s0bjd00000gn/T/ipykernel_38714/407161840.py:10: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  name = row[-2]
/var/folders/n0/lqgykh5n5s5f6fk5p0s0bjd00000gn/T/ipykernel_38714/407161840.py:11: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  num = row[-1]

['Ryan Pal Hilgendorf',
 'Ryan Pal Hilgendorf',
 'Alex Ewart',
 'Alex Ewart',
 'Alex Ewart',
 'Michael Link',
 'Zoe Kirkman',
 'Michael Link',
 'Kathlyn Leanos',
 'Kathlyn Leanos',
 'Kathlyn Leanos',
 'Kathlyn Leanos',
 'Kathlyn Leanos',
 'Kathlyn Leanos',
 'Jack LeCloux',
 'Mason Beynon',
 'Hugo garrido-lestache',
 'Leigh Goetsch',
 'Vincenzo Bean ',
 'Sydney Balboni',
 'Sydney Balboni',
 'Sydney Balboni',
 'Sydney Balboni',
 'Sydney Balboni',
 'Sydney Balboni',
 'Sydney Balboni',
 'Sydney Balboni',
 'Sydney Balboni',
 'Sydney Balboni',
 'Sydney Balboni',
 'Sydney Balboni',
 'Sydney Balboni',
 'Sydney Balboni',
 'Sydney Balboni',
 'Sydney Balboni',
 'Sydney Balboni',
 'Sydney Balboni',
 'Sydney Balboni',
 'Sydney Balboni',
 'Sydney Balboni',
 'Sydney Balboni',
 'Sydney Balboni',
 'Sydney Balboni',
 'Sydney Balboni',
 'Sydney Balboni',
 'Sydney Balboni',
 'Sydney Balboni',
 'Sydney Balboni',
 'Sydney Balboni',
 'Sydney Balboni',
 'Sydney Balboni',
 'Sydney Balboni',
 'Sydney Balboni',
 'Sydney Balboni',
 'Sydney Balboni',
 'Sydney Balboni',
 'Sydney Balboni',
 'Sydney Balboni',
 'Sydney Balboni',
 'Sydney Balboni',
 'Sydney Balboni',
 'Sydney Balboni',
 'Sydney Balboni',
 'Sydney Balboni',
 'Sydney Balboni',
 'Sydney Balboni',
 'Sydney Balboni',
 'Sydney Balboni',
 'Sydney Balboni',
 'Sydney Balboni',
 'Kelsey collins ',
 'Kelsey collins ',
 'Kelsey collins ',
 'Kelsey collins ',
 'Alhagie Boye',
 'Miles Trompeter',
 'Miles Trompeter',
 'Miles Trompeter',
 'Miles Trompeter',
 'Miles Trompeter',
 'Oskar Sierzega',
 'Lexi Dorner',
 'Charles BioloThompson',
 'Alexander Lopez',
 'Alex Toma',
 'Alex Toma',
 'Austin Koske',
 'Reagan Burkemper',
 'Oliver Grudzinski ',
 'Michael Wood',
 'Raegan Pelnar',
 'Isabella Ruiz',
 'Samantha DeLisi',
 'Gabrielle Sladek',
 'Jake Weiland',
 'Xander Ede',
 'Mikhail Filippov',
 'Mikhail Filippov',
 'Mikhail Filippov',
 'Mikhail Filippov',
 'Mikhail Filippov',
 'Hayden Park',
 'Vlad Wilson',
 'Joseph Beattie',
 'Andrew Needham',
 'Andrew Needham',
 'Andrew Needham',
 'Andrew Needham',
 'Andrew Needham',
 'Andrew Needham',
 'Andrew Needham',
 'Andrew Needham',
 'Andrew Needham',
 'Andrew Needham',
 'Andrew Needham',
 'Andrew Needham',
 'Andrew Needham',
 'Benjamin Leshin',
 'Benjamin Leshin',
 'Benjamin Leshin',
 'Benjamin Leshin',
 'Benjamin Leshin',
 'Patrick Rafferty',
 'Will Lassiter',
 'Jacob Kyllo',
 'Zak Goetter',
 'Zak Goetter',
 'Zak Goetter',
 'Zak Goetter',
 'Zak Goetter',
 'Trevor Hancock',
 'Trevor Hancock',
 'Trevor Hancock',
 'Trevor Hancock',
 'Trevor Hancock',
 'Trevor Hancock',
 'Trevor Hancock',
 'Trevor Hancock',
 'Trevor Hancock',
 'Travis Jankowski',
 'Travis Jankowski',
 'John Balasbas',
 'Josiah Reinholz',
 'Josiah Reinholz',
 'Josiah Reinholz',
 'Josiah Reinholz',
 'Josiah Reinholz',
 'Josiah Reinholz',
 'Josiah Reinholz',
 'Owen Jacobsen',
 'Sydney Madden']

### Better DF Format
Get the df into a format which is easy to remove the points from the online leaderboard

In [9]:
# For df, replace all Nan values with 0 (Free point)
df = df.fillna(0)

# Rename the first column to 'Name' and the second column to 'Points'
df.columns = ['Name', 'Points']
df

# For each name, get rid of white space surrounding the name and title the string
df['Name'] = df['Name'].str.strip().str.title()
df

                     Name  Points
0     Ryan Pal Hilgendorf       1
1              Alex Ewart       2
2            Michael Link       0
3             Zoe Kirkman       0
4            Michael Link       0
5          Kathlyn Leanos       5
6            Jack Lecloux       0
7            Mason Beynon       0
8   Hugo Garrido-Lestache       0
9           Leigh Goetsch       0
10          Vincenzo Bean       0
11         Sydney Balboni      50
12         Kelsey Collins       3
13           Alhagie Boye       0
14        Miles Trompeter       4
15         Oskar Sierzega       0
16            Lexi Dorner       0
17  Charles Biolothompson       0
18        Alexander Lopez       0
19              Alex Toma       1
20           Austin Koske       0
21       Reagan Burkemper       0
22      Oliver Grudzinski       0
23           Michael Wood       0
24          Raegan Pelnar       0
25          Isabella Ruiz       0
26        Samantha Delisi       0
27       Gabrielle Sladek       0
28           Jake Weiland       0
29             Xander Ede       0
30       Mikhail Filippov       4
31            Hayden Park       0
32            Vlad Wilson       0
33         Joseph Beattie       0
34         Andrew Needham      12
35        Benjamin Leshin       4
36       Patrick Rafferty       0
37          Will Lassiter       0
38            Jacob Kyllo       0
39            Zak Goetter       4
40         Trevor Hancock       8
41       Travis Jankowski       1
42          John Balasbas       0
43        Josiah Reinholz       6
44          Owen Jacobsen       0
45          Sydney Madden       0

In [10]:
user_data = pd.read_csv('../../data/User_Data.csv')
user_data

,User,Description,Awards,All-Time Points,Current Points,First Name,Last Name
0,Ben Paulson,test description,Hacksgiving|ROSIE Competition Finalist 2024|NV...,14,14,Ben,Paulson
1,Lucas Gral,test description,Overlord|eboard2022|eboard2023|eboard2024|2022...,37,37,Lucas,Gral
2,Sydney Balboni,test description,ROSIE Presenter|Hacksgiving|2024 Researcher|20...,50,49,Sydney,Balboni
3,John Cisler,test description,Hacksgiving|ROSIE Competition Finalist 2024|RO...,15,14,John,Cisler
4,Evan Schubert,test description,2024 Researcher|2024 MICS Attendee,14,14,Evan,Schubert
...,...,...,...,...,...,...,...
363,Sam Mcclure,test description,NaN,1,0,NaN,NaN
364,Madalyne Broennimann,test description,NaN,1,1,NaN,NaN
365,Mathias Galvan,test description,NaN,1,0,NaN,NaN
366,Zain Aayaan Mohammed,test description,NaN,1,1,NaN,NaN
367,Owen Jacobsen,test description,NaN,35,35,NaN,NaN

In [11]:
user_data[user_data['User'] == 'Caleb Gray']

,User,Description,Awards,All-Time Points,Current Points,First Name,Last Name
141,Caleb Gray,test description,2024 Researcher|2024 MICS Attendee|ROSIE Compe...,38,28,Caleb,Gray

In [12]:
# Given the amount of points associated with each Name in df, remove those points from user_data 'Current Points'
for index, row in df.iterrows():
    name = row['Name']
    points = row['Points']
    
    # Find the index of the name in user_data
    user_index = user_data[user_data['User'] == name]

    # If user index empty, skip
    if user_index.empty:
        continue

    # Get the index of the user
    user_index = user_index.index[0]
    
    # Subtract the points from the 'Current Points' column
    user_data.loc[user_index, 'Current Points'] = user_data.loc[user_index, 'Current Points'] - points

    print(f"Subtracting {points} from {name}'s Current Point, resulting in {user_data.loc[user_index, 'Current Points']}")

user_data[user_data['User'] == 'Caleb Gray']

Subtracting 1 from Ryan Pal Hilgendorf's Current Point, resulting in 0
Subtracting 2 from Alex Ewart's Current Point, resulting in 14
Subtracting 0 from Michael Link's Current Point, resulting in 9
Subtracting 0 from Zoe Kirkman's Current Point, resulting in 15
Subtracting 0 from Michael Link's Current Point, resulting in 9
Subtracting 0 from Jack Lecloux's Current Point, resulting in 15
Subtracting 0 from Mason Beynon's Current Point, resulting in 16
Subtracting 0 from Hugo Garrido-Lestache's Current Point, resulting in 3
Subtracting 0 from Leigh Goetsch's Current Point, resulting in 12
Subtracting 0 from Vincenzo Bean's Current Point, resulting in 0
Subtracting 50 from Sydney Balboni's Current Point, resulting in -1
Subtracting 3 from Kelsey Collins's Current Point, resulting in -1
Subtracting 0 from Alhagie Boye's Current Point, resulting in 37
Subtracting 4 from Miles Trompeter's Current Point, resulting in 20
Subtracting 0 from Oskar Sierzega's Current Point, resulting in 3
Subtracting 0 from Lexi Dorner's Current Point, resulting in 1
Subtracting 0 from Alexander Lopez's Current Point, resulting in 42
Subtracting 1 from Alex Toma's Current Point, resulting in 6
Subtracting 0 from Austin Koske's Current Point, resulting in 24
Subtracting 0 from Reagan Burkemper's Current Point, resulting in 14
Subtracting 0 from Oliver Grudzinski's Current Point, resulting in 5
Subtracting 0 from Michael Wood's Current Point, resulting in 16
Subtracting 0 from Isabella Ruiz's Current Point, resulting in 18
Subtracting 0 from Gabrielle Sladek's Current Point, resulting in 39
Subtracting 0 from Jake Weiland's Current Point, resulting in 7
Subtracting 0 from Xander Ede's Current Point, resulting in 10
Subtracting 4 from Mikhail Filippov's Current Point, resulting in 15
Subtracting 0 from Hayden Park's Current Point, resulting in 9
Subtracting 0 from Vlad Wilson's Current Point, resulting in 23
Subtracting 0 from Joseph Beattie's Current Point, resulting in 9
Subtracting 12 from Andrew Needham's Current Point, resulting in 0
Subtracting 4 from Benjamin Leshin's Current Point, resulting in 8
Subtracting 0 from Patrick Rafferty's Current Point, resulting in 51
Subtracting 0 from Will Lassiter's Current Point, resulting in 7
Subtracting 4 from Zak Goetter's Current Point, resulting in 18
Subtracting 8 from Trevor Hancock's Current Point, resulting in 0
Subtracting 1 from Travis Jankowski's Current Point, resulting in 55
Subtracting 0 from John Balasbas's Current Point, resulting in 2
Subtracting 6 from Josiah Reinholz's Current Point, resulting in 0
Subtracting 0 from Owen Jacobsen's Current Point, resulting in 35
Subtracting 0 from Sydney Madden's Current Point, resulting in 7

,User,Description,Awards,All-Time Points,Current Points,First Name,Last Name
141,Caleb Gray,test description,2024 Researcher|2024 MICS Attendee|ROSIE Compe...,38,28,Caleb,Gray

In [13]:
user_data.to_csv('../../data/User_Data.csv', index=False)